language: r
warnings_are_errors: true

r_packages:
  - RUnit
r_binary_packages:
  - mirtCAT
  - knitr
  - testthat
  - devtools

r_github_packages:
  - philchalmers/mirt

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - _R_CHECK_FORCE_SUGGESTS_=0

script:
  - make install
  - make check
  - make test
